// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd0YpVTE8aspZc4-F5rH-m6YcYltSsEpE',
    appId: '1:468682191943:web:342ff9f6782dccbe6aad62',
    messagingSenderId: '468682191943',
    projectId: 'chat-flutter-8cf3b',
    authDomain: 'chat-flutter-8cf3b.firebaseapp.com',
    storageBucket: 'chat-flutter-8cf3b.appspot.com',
    measurementId: 'G-731R38RVT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpJCcE2okOLissI6TIzfkAmDwyh_y2_0',
    appId: '1:468682191943:android:1ddeab8c281ef6096aad62',
    messagingSenderId: '468682191943',
    projectId: 'chat-flutter-8cf3b',
    storageBucket: 'chat-flutter-8cf3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9WvsM4fkWkpvwgKoEsJ5xaQ1iaP932-E',
    appId: '1:468682191943:ios:2abac1ffdf3f23526aad62',
    messagingSenderId: '468682191943',
    projectId: 'chat-flutter-8cf3b',
    storageBucket: 'chat-flutter-8cf3b.appspot.com',
    iosBundleId: 'com.example.chatflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9WvsM4fkWkpvwgKoEsJ5xaQ1iaP932-E',
    appId: '1:468682191943:ios:2abac1ffdf3f23526aad62',
    messagingSenderId: '468682191943',
    projectId: 'chat-flutter-8cf3b',
    storageBucket: 'chat-flutter-8cf3b.appspot.com',
    iosBundleId: 'com.example.chatflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd0YpVTE8aspZc4-F5rH-m6YcYltSsEpE',
    appId: '1:468682191943:web:20782a0a49c641596aad62',
    messagingSenderId: '468682191943',
    projectId: 'chat-flutter-8cf3b',
    authDomain: 'chat-flutter-8cf3b.firebaseapp.com',
    storageBucket: 'chat-flutter-8cf3b.appspot.com',
    measurementId: 'G-LNQQZBLQ49',
  );
}
